[package]
name = "4x8matrix/infinity"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = "Unlicense"
authors = ["AsynchronousMatrix"]

description = ""

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml", "LICENCE", "README.md"]

# [dev-dependencies]
# TestEz = "roblox/testez@0.4.1"

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.6"
